/* Do not edit this file: It has been generated by combining block ids, names and metadata on the server. */

export const BlockDefinitions = {
  "1": {
    "data": {
      "texture": [
        "stone0.png"
      ],
      "hardness": 1.5,
      "blast_resistance": 6,
      "loaded": 1753422969175
    },
    "key": "STONE",
    "id": 1
  },
  "2": {
    "data": {
      "loaded": 1753422969176
    },
    "key": "COPPER_ORE",
    "id": 2
  },
  "3": {
    "data": {
      "texture": "water_still.png",
      "loaded": 1753422969176
    },
    "key": "WATER",
    "id": 3
  },
  "4": {
    "data": {
      "key": "GRANITE",
      "texture": "granite.png",
      "loaded": 1753422969177
    },
    "key": "GRANITE",
    "id": 4
  },
  "5": {
    "data": {
      "texture": [
        "grass_path_top.png",
        "grass_path_side.png",
        "dirt.png"
      ],
      "hardness": 0.6,
      "name": "Grass Block",
      "id": 2,
      "type": "block",
      "is_solid": true,
      "is_transparent": false,
      "is_opaque": true,
      "is_flammable": false,
      "is_mineable_with_shovel": true,
      "is_mineable_with_pickaxe": false,
      "is_mineable_with_axe": false,
      "is_mineable_with_hoe": false,
      "loaded": 1753422969178
    },
    "key": "GRASS_BLOCK",
    "id": 5
  },
  "6": {
    "data": {
      "texture": "oak_log.png",
      "loaded": 1753422969178
    },
    "key": "OAK_LOG",
    "id": 6
  },
  "7": {
    "data": {
      "texture": "unknown.png",
      "loaded": 1753422969178
    },
    "key": "SHORT_GRASS",
    "id": 7
  },
  "8": {
    "data": {
      "texture": "oak_leaves.png",
      "loaded": 1753422969179
    },
    "key": "OAK_LEAVES",
    "id": 8
  },
  "9": {
    "data": {
      "key": "BIRCH_LOG",
      "texture": "birch_log.png",
      "loaded": 1753422969179
    },
    "key": "BIRCH_LOG",
    "id": 9
  },
  "10": {
    "data": null,
    "key": "BIRCH_LEAVES",
    "id": 10
  },
  "11": {
    "data": {
      "key": "DIRT",
      "texture": "dirt.png",
      "loaded": 1753422969179
    },
    "key": "DIRT",
    "id": 11
  },
  "12": {
    "data": {
      "key": "ACACIA_LEAVES",
      "texture": "acacia_leaves.png",
      "loaded": 1753422969180
    },
    "key": "ACACIA_LEAVES",
    "id": 12
  },
  "13": {
    "data": {
      "key": "ANDESITE",
      "texture": "andesite.png",
      "loaded": 1753422969180
    },
    "key": "ANDESITE",
    "id": 13
  },
  "14": {
    "data": null,
    "key": "GLOW_LICHEN",
    "id": 14
  },
  "15": {
    "data": null,
    "key": "DIORITE",
    "id": 15
  },
  "16": {
    "data": {
      "key": "GRAVEL",
      "texture": "gravel.png",
      "loaded": 1753422969181
    },
    "key": "GRAVEL",
    "id": 16
  },
  "17": {
    "data": {
      "key": "JUNGLE_LEAVES",
      "texture": "jungle_leaves.png",
      "loaded": 1753422969181
    },
    "key": "JUNGLE_LEAVES",
    "id": 17
  },
  "18": {
    "data": {
      "key": "VINE",
      "texture": "vine.png",
      "loaded": 1753422969181
    },
    "key": "VINE",
    "id": 18
  },
  "19": {
    "data": null,
    "key": "COAL_ORE",
    "id": 19
  },
  "20": {
    "data": {
      "texture": [
        "jungle_log.png",
        "jungle_log_top.png"
      ],
      "hardness": 2,
      "resistance": 5,
      "flammable": true,
      "flammability": 5,
      "burns": true,
      "tool": "axe",
      "tool_level": 0,
      "transparent": false,
      "solid": true,
      "opaque": true,
      "collision_box": {
        "type": "block",
        "size": [
          1,
          1,
          1
        ]
      },
      "light_emission": 0,
      "loaded": 1753422969182
    },
    "key": "JUNGLE_LOG",
    "id": 20
  },
  "21": {
    "data": {
      "texture": "fern.png",
      "loaded": 1753422969182
    },
    "key": "FERN",
    "id": 21
  },
  "22": {
    "data": {
      "texture": "iron_ore.png",
      "loaded": 1753422969182
    },
    "key": "IRON_ORE",
    "id": 22
  },
  "23": {
    "data": {
      "texture": "dandelion.png",
      "loaded": 1753422969183
    },
    "key": "DANDELION",
    "id": 23
  }
};
