const block_data = [{
	id: 1,
	texture: "stone.png"
}, {
	id: 2,
	texture: {
		top: "grass_green.png",
		left: "grass_side.png",
		right: "grass_side.png",
		front: "grass_side.png",
		back: "grass_side.png",
		bottom: "dirt.png"
	}
}, {
	id: 3,
	texture: "dirt.png"
}, {
	id: 4,
	texture: "cobblestone.png"
}, {
	id: 5,
	texture: "planks_oak.png"
}, {
	id: 6,
	texture: "sapling_oak.png",
	special: true
}, {
	id: 7,
	texture: "bedrock.png"
}, {
	id: 12,
	texture: "sand.png"
}, {
	id: 13,
	texture: "gravel.png"
}, {
	id: 14,
	texture: "gold_ore.png"
}, {
	id: 15,
	texture: "iron_ore.png"
}, {
	id: 16,
	texture: "coal_ore.png"
}, {
	id: 17,
	texture: {
		top: "log_oak_top.png",
		left: "log_oak.png",
		right: "log_oak.png",
		front: "log_oak.png",
		back: "log_oak.png",
		bottom: "log_oak_top.png"
	}
}, {
	id: 18,
	texture: "leaves_oak_opaque.png"
}, {
	id: 19,
	texture: "sponge.png"
}, {
	id: 20,
	texture: "glass.png",
	special: true
}, {
	id: 21,
	texture: "lapis_ore.png"
}, {
	id: 22,
	texture: "lapis_block.png"
}, {
	id: 23,
	texture: {
		top: "furnace_top.png",
		left: "furnace_side.png",
		right: "furnace_side.png",
		front: "dispenser_front_horizontal.png",
		back: "furnace_side.png",
		bottom: "furnace_top.png"
	}
}, {
	id: 24,
	texture: {
		top: "sandstone_top.png",
		left: "sandstone_normal.png",
		right: "sandstone_normal.png",
		front: "sandstone_normal.png",
		back: "sandstone_normal.png",
		bottom: "sandstone_bottom.png"
	}
}, {
	id: 25,
	texture: "noteblock.png"
}, {
	id: 27,
	texture: "rail_golden_powered.png",
	special: true
}, {
	id: 28,
	texture: "rail_detector.png",
	special: true
}, {
	id: 29,
	texture: {
		top: "piston_top_sticky.png",
		left: "piston_side.png",
		right: "piston_side.png",
		front: "piston_side.png",
		back: "piston_side.png",
		bottom: "piston_bottom.png"
	}
}, {
	id: 33,
	texture: {
		top: "piston_top_normal.png",
		left: "piston_side.png",
		right: "piston_side.png",
		front: "piston_side.png",
		back: "piston_side.png",
		bottom: "piston_bottom.png"
	}
}, {
	id: 35,
	texture: "wool_colored_white.png"
}, {
	id: 41,
	texture: "gold_block.png"
}, {
	id: 42,
	texture: "iron_block.png"
}, {
	id: 43,
	texture: {
		top: "stone_slab_top.png",
		left: "stone_slab_side.png",
		right: "stone_slab_side.png",
		front: "stone_slab_side.png",
		back: "stone_slab_side.png",
		bottom: "stone_slab_top.png"
	}
}, {
	id: 45,
	texture: "brick.png"
}, {
	id: 46,
	texture: {
		top: "tnt_top.png",
		left: "tnt_side.png",
		right: "tnt_side.png",
		front: "tnt_side.png",
		back: "tnt_side.png",
		bottom: "tnt_bottom.png"
	}
}, {
	id: 47,
	texture: {
		top: "planks_oak.png",
		left: "bookshelf.png",
		right: "bookshelf.png",
		front: "bookshelf.png",
		back: "bookshelf.png",
		bottom: "planks_oak.png"
	}
}, {
	id: 48,
	texture: "cobblestone_mossy.png"
}, {
	id: 49,
	texture: "obsidian.png"
}, {
	id: 50,
	texture: "torch_on.png",
	special: true
}, {
	id: 56,
	texture: "diamond_ore.png"
}, {
	id: 57,
	texture: "diamond_block.png"
}, {
	id: 58,
	texture: {
		top: "crafting_table_top.png",
		left: "crafting_table_side.png",
		right: "crafting_table_side.png",
		front: "crafting_table_front.png",
		back: "crafting_table_front.png",
		bottom: "planks_oak.png"
	}
}, {
	id: 61,
	texture: {
		top: "furnace_top.png",
		left: "furnace_side.png",
		right: "furnace_side.png",
		front: "furnace_front_off.png",
		back: "furnace_side.png",
		bottom: "furnace_top.png"
	}
}, {
	id: 62,
	texture: "rail_normal.png",
	special: true
}, {
	id: 64,
	texture: "door_wood_lower.png",
	special: true
}, {
	id: 69,
	texture: "lever.png",
	special: true
}, {
	id: 69,
	texture: "stone.png",
	special: true
}, {
	id: 71,
	texture: "door_iron_lower.png",
	special: true
}, {
	id: 72,
	texture: "planks_oak.png",
	special: true
}, {
	id: 73,
	texture: "redstone_ore.png"
}, {
	id: 74,
	texture: "redstone_ore.png"
}, {
	id: 75,
	texture: "redstone_torch_off.png",
	special: true
}, {
	id: 76,
	texture: "redstone_torch_on.png",
	special: true
}, {
	id: 77,
	texture: "stone.png",
	special: true
}, {
	id: 79,
	texture: "ice.png"
}, {
	id: 80,
	texture: "snow.png"
}, {
	id: 81,
	texture: {
		top: "cactus_top.png",
		left: "cactus_side.png",
		right: "cactus_side.png",
		front: "cactus_side.png",
		back: "cactus_side.png",
		bottom: "cactus_bottom.png"
	},
	special: true
}, {
	id: 82,
	texture: "clay.png"
}, {
	id: 87,
	texture: "netherrack.png"
}, {
	id: 88,
	texture: "soul_sand.png"
}, {
	id: 89,
	texture: "glowstone.png"
}, {
	id: 93,
	texture: "repeater_off.png",
	special: true
}, {
	id: 94,
	texture: "repeater_on.png",
	special: true
}, {
	id: 95,
	texture: "trapdoor.png",
	special: true
}, {
	id: 98,
	texture: "stonebrick.png",
	special: true
}, {
	id: 121,
	texture: "end_stone.png"
}, {
	id: 149,
	texture: "comparator_off.png",
	special: true
}, {
	id: 150,
	texture: "comparator_on.png",
	special: true
}, {
	id: 155,
	texture: "quartz_block_top.png"
}, {
	id: 157,
	texture: "rail_activator.png",
	special: true
}, {
	id: 159,
	texture: "hardened_clay_stained_white.png"
}, {
	id: 160,
	texture: "planks_spruce.png"
}, {
	id: 161,
	texture: "planks_birch.png"
}, {
	id: 162,
	texture: "planks_jungle.png"
}, {
	id: 163,
	texture: "planks_acacia.png"
}, {
	id: 164,
	texture: "planks_big_oak.png"
}, {
	id: 168,
	texture: "stonebrick.png"
}, {
	id: 169,
	texture: "stonebrick_carved.png"
}, {
	id: 169,
	texture: "stonebrick_cracked.png"
}, {
	id: 169,
	texture: "stonebrick_mossy.png"
}, {
	id: 181,
	texture: "wool_colored_orange.png"
}, {
	id: 182,
	texture: "wool_colored_magenta.png"
}, {
	id: 183,
	texture: "wool_colored_light_blue.png"
}, {
	id: 184,
	texture: "wool_colored_yellow.png"
}, {
	id: 185,
	texture: "wool_colored_lime.png"
}, {
	id: 186,
	texture: "wool_colored_pink.png"
}, {
	id: 187,
	texture: "wool_colored_gray.png"
}, {
	id: 188,
	texture: "wool_colored_silver.png"
}, {
	id: 189,
	texture: "wool_colored_cyan.png"
}, {
	id: 190,
	texture: "wool_colored_purple.png"
}, {
	id: 191,
	texture: "wool_colored_blue.png"
}, {
	id: 192,
	texture: "wool_colored_brown.png"
}, {
	id: 193,
	texture: "wool_colored_green.png"
}, {
	id: 194,
	texture: "wool_colored_red.png"
}, {
	id: 195,
	texture: "wool_colored_black.png"
}, {
	id: 196,
	parent: 17,
	rotation: [0, Math.PI, 0]
}, {
	id: 200,
	texture: "redstone_lamp_off.png"
}, {
	id: 201,
	texture: "redstone_lamp_on.png"
}];
